# -*- coding: utf-8 -*-
"""My EDA project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LljI4lHPlxik2Dw_6P1ncFNvhektaGeF

# **FINAL 'EDA' PROJECT1:**

---


## "Introduction of the Dataset:"

---


This project analyzes the **HR Employee Attrition** dataset.The dataset contains 35 features about the employees.
[https://drive.google.com/file/d/1Wv6kJD_MwBYFnshEn_Y9_KmP_cp3eSE_/view?usp=drive_link](https://)

## "Project Objective:"

---


The main objective of this project is to identify the key factors that cause employees to leave the company.

## What We Are Going to Analyze ("Questions"):

---


1. What is the overall attrition rate in the company?
2. How does age and distance from home affect employee attrition?
3. Does a lower salary (Monthly Income) force employees to leave?
4. How does working Overtime or business travelling  impact an employee's decision to stay or leave?

# **1. DATA UNDERSTANDING**

In this step we'll import libraries and understand our data so we can get better results.
"""

#import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv("/content/HR-Employee-Attrition.csv")
data

"""###  Data Overview
We check the shape, columns, and basic structure of the dataset.
"""

data.shape

data.head(5)

data.tail(8)

data.sample(n = 10)

data.columns

"""By using the info Syntex we can see the null rows and the data type of the columns."""

data.info()

"""To calculate total count, mean, std, min, max, and the quartiles we can use ". describe ()"
"""

data.describe()

data.dtypes

"""# **2. DATA CLEANING**

###  Handling Missing Values
We check for null values and handle them appropriately.
"""

data.isnull().sum()

"""To check if there's any duplicate values we use the following method to remove the duplicate rows."""

data.duplicated().sum()

"""Check number of unique value in each column by using the following method."""

# Check number of unique values in each column
for col in data.columns:
    print(col, ":", data[col].nunique())

# Columns identified as irrelevant or low impact
cols_to_drop = [
    'EmployeeCount',
    'EmployeeNumber',
    'Over18',
    'StandardHours',
    'DailyRate',
    'HourlyRate',
    'MonthlyRate'
]
# Drop unnecessary columns
data.drop(columns=cols_to_drop, inplace=True, errors='ignore')

# Check new shape
print("Shape after removing columns:", data.shape)

"""“I checked each column using unique values and visual analysis. Columns with no variation, identifier columns, and those showing weak relationship with attrition were removed.”"""

data.sample(5)                  #.................After removing weak related or unnecessary columns

for col in data.columns:
    print(col, data[col].nunique())

"""# Checking OUtliers

Checking the outliers of the strongest related columns will give us the accurate predictions.
"""

num_cols = ['Age','MonthlyIncome','DistanceFromHome','TotalWorkingYears','YearsAtCompany']

for col in num_cols:
    sns.boxplot(x=data[col])
    plt.title(f"Outliers in {col}")
    plt.show()

    #“Outliers were observed in features such as MonthlyIncome and TotalWorkingYears.
    #However, these values were retained as they represent real-world employee variations rather than errors.”

"""###  Handling Outliers using IQR Method (Clipping)

In this step, we detect and handle outliers using the IQR (Interquartile Range) method.

- Q1 = 25th percentile  
- Q3 = 75th percentile  
- IQR = Q3 - Q1  

We define:
- Lower Limit = Q1 - 1.5 * IQR  
- Upper Limit = Q3 + 1.5 * IQR  

Any values outside this range are considered outliers.

Instead of removing them, we **clip** them to the boundary values.
"""

# Copy dataset for safe processing
df_clipped = data.copy()

# Select only numeric columns
numeric_cols = df_clipped.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    Q1 = df_clipped[col].quantile(0.25)
    Q3 = df_clipped[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Clipping outliers
    df_clipped[col] = df_clipped[col].clip(lower, upper)

print("Outliers have been handled using clipping.")

"""###  Before vs After Outlier Handling"""

col = "MonthlyIncome"

plt.figure(figsize=(10,4))

# Before clipping
plt.subplot(1,2,1)
plt.boxplot(data[col])
plt.title("Before Clipping")
plt.ylabel(col)

# After clipping
plt.subplot(1,2,2)
plt.boxplot(df_clipped[col])
plt.title("After Clipping")

plt.tight_layout()
plt.show()

""""Before clipping, income column had extreme values (outliers)"

"After clipping, those values were adjusted within IQR range"

"Distribution is now more balanced and less skewed"

# **3. EDA(univarient, bivarient, insights)**

**univarient**

attrition rate in the company can be seen through histogram.
"""

data['Attrition'].hist()

"""Most employees have not left the company.

check the skewness of the columns
"""

import pandas as pd

# assume df tumhara dataset hai
skew_values = data.skew(numeric_only=True)

print(skew_values)

""" **remove the skewness of the columns**"""

skewed_cols = skew_values[(skew_values > 1) | (skew_values < -1)]

print("Skewed Columns:\n", skewed_cols)

import numpy as np

for col in skewed_cols.index:
    data[col] = np.log1p(data[col])

"""**after the skewness is handled**"""

print(data[skewed_cols.index].skew())

sns.countplot(x='OverTime', data=data)
plt.title("OverTime Distribution")
plt.show()

"""Majority of employees do not work overtime."""

#distance from effect attribution???
sns.histplot(data['DistanceFromHome'], kde=True)
plt.title("Distance From Home Distribution")
plt.show()

"""Employees living farther from home may have slightly higher attrition."""

sns.countplot(x='Gender', data=data)
plt.title("Gender Distribution")
plt.show()

"""Dataset contains more male employees than female."""

sns.histplot(data['Age'], kde=True)
plt.title("Age Distribution")
plt.show()

"""Most employees are between 25–40 years.

**bivarient**

**numerical vs categorical**
"""

#does age matters???
plt.scatter(data["Age"], data["Attrition"])
plt.xlabel("Age")
plt.ylabel("Attrition")
plt.title("Age vs Attrition")
plt.show()

"""**numerical vs categorical**"""

#does salary effect attribution
plt.scatter(data["MonthlyIncome"], data["Attrition"])
plt.xlabel("MonthlyIncome")
plt.ylabel("Attrition")
plt.title("Monthly Income vs Attrition")
plt.show()

"""**categorical vs categorical**"""

result = pd.crosstab(data['BusinessTravel'], data['Attrition'], normalize='index') * 100
print(result)

sns.countplot(x='BusinessTravel', hue='Attrition', data=data)
plt.title("Business Travel vs Attrition")
plt.show()

"""Employees who travel frequently show higher attrition percentage compared to those who travel rarely.

**categorical vs categorical**
"""

pd.crosstab(data['OverTime'], data['Attrition'], normalize='index') * 100

#what impact does oveertime have on attribution???
pd.crosstab(data['OverTime'], data['Attrition']).plot(kind='bar')
plt.title("OverTime vs Attrition")
plt.xlabel("OverTime")
plt.ylabel("Count")
plt.show()

"""**OverTime:**

Employees working overtime tend to leave more

# **multivarient**

### Multivariate Analysis
We analyze relationships between multiple variables.
"""

plt.figure(figsize=(8,5))

sns.scatterplot(
    x='Age',
    y='MonthlyIncome',
    hue='Attrition',
    size='TotalWorkingYears',
    data=data,
    alpha=0.7
)

plt.title("Age vs MonthlyIncome (Attrition + Experience)")
plt.show()

"""# **Insights:**
*   Employees with lower income and lower age show higher attrition tendency
*   Income generally increases with age and experience
*   Larger bubbles (high experience) mostly correspond to higher income and lower attrition

# **4. DATA VISUALIZATION (correlation)**

###  Data Visualization
We visualize relationships between variables using plots.
"""

important_cols = [
    'Age',
    'MonthlyIncome',
    'TotalWorkingYears',
    'YearsAtCompany',
    'DistanceFromHome'
]
corr = data[important_cols].corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

"""# **Insights:**
1. Age and TotalWorkingYears show strong positive correlation
2. MonthlyIncome increases with experience
3. DistanceFromHome shows weak correlation with other variables

# **5. Answers of the Business Questions**

Q1: What is the overall attrition rate?
"""

data['Attrition'].value_counts(normalize=True) * 100

"""The overall attrition rate shows that a certain percentage of employees have left the company, while the majority have stayed. This indicates moderate employee retention in the organization

---

Q2: Age and Distance from Home effect?
"""

sns.boxplot(x='Attrition', y='Age', data=data)
sns.boxplot(x='Attrition', y='DistanceFromHome', data=data)

"""Younger employees are more likely to leave the company compared to older employees. Distance from home shows a weaker relationship, but employees living farther away may have a slightly higher tendency to leave

---

Q3: Salary effect??

---
"""

sns.boxplot(x='Attrition', y='MonthlyIncome', data=data)

"""Employees with lower monthly income show a higher attrition rate. This suggests that salary plays an important role in employee retention

---

Q4: Overtime + Business Travel effect???
"""

pd.crosstab(data['OverTime'], data['Attrition'], normalize='index') * 100
sns.countplot(x='BusinessTravel', hue='Attrition', data=data)

"""Employees who work overtime are more likely to leave the company compared to those who do not. Similarly, employees who travel frequently for business show a higher attrition rate than those who rarely travel.

# **6. Insights & Recommendations:**

### Major Finding 1: Overtime and Burnout
 **Observation:** Employees who are doing overtime have a noticeably higher attrition rate.

 **Insight:** Overtime causes mental and physical burnout, forcing people to quit for a better work-life balance.

 **Decision:** The company should restrict mandatory overtime or offer flexible working hours. If extra work is needed, they should hire more staff instead of overburdening current employees.

### Major Finding 2: Low Salary is a Dealbreaker
 **Observation:** The median `MonthlyIncome` of people who leave is much lower than those who stay.

 **Insight:** Employees are mostly leaving for better financial opportunities.

 **Decision:** HR should review the salaries of entry-level and mid-level employees to ensure they match market standards. Provide yearly bonuses or performance hikes.

### Major Finding 3: The Danger Zone (First 2 Years & Young Age)
 **Observation:** Young professionals (ages 25-32) and employees in their first 1-2 years at the company leave the most.

 **Insight:** Young talent is highly mobile. The onboarding process or early-career growth path might not be satisfying.

 **Decision:** Introduce mentorship programs for new joiners. Show them a clear career progression path so they feel valued and stay longer.

#**7. Final Conclusion:**

#Overall Summary:
Through our Exploratory Data Analysis of the HR Attrition Dataset, we discovered that employee turnover is not random. It is heavily influenced by factors like low salary, high overtime, young age, and the early years of employment. Job roles like Laboratory Technicians and Sales Representatives are at the highest risk.

#Top 3 Business Recommendations:
1. **Regulate Workload:** Strictly monitor and limit overtime to prevent employee burnout.
2. **Revise Compensation Plans:** Ensure that starting salaries and monthly incomes for high-risk roles (like Sales and Lab Techs) are competitive.
3. **Focus on Retention of New Joiners:** Create specific engaging programs, training, and bonding activities for employees in their first 2 years to build loyalty.(service agreement)
"""

